### ISSUE TITLE
Red channel shifted

### ISSUE THREAD

**Issue by nlimper** [jjwbruijn/solum-esl-alternative-proto#5]
In the latest tag_fw (tried with yesterday's and latest version), the red channel is shifted about 8 pixels to the right (seen from portrait orientation). Tried with multiple tags.
![IMG_7439](https://user-images.githubusercontent.com/4137036/215491553-fb849109-c730-48b5-9829-8560bfcee6a7.jpeg)

**Comment by jjwbruijn** [comment]
Can confirm, Drake wasn't happy.
![image](https://user-images.githubusercontent.com/2544995/215507223-53ba43cc-21df-43ae-a835-0212e3bd2bf3.png)

Drake is happy again with push https://github.com/jjwbruijn/solum-esl-alternative-proto/commit/0f0c86d5f88be2d09458ef48f10d9e41f6a4654e
![image](https://user-images.githubusercontent.com/2544995/215507312-bb90d1c5-7e27-4f0d-bce8-28d564f4b8b4.png)

**Comment by jjwbruijn** [comment]
Still broken, Don't know how, Don't know why :)

**Comment by jjwbruijn** [comment]
Should be fixed now...

**Comment by nlimper** [comment]
nope... :-(  Checked with latest firmware of today.
btw also the black channel is wrapped around a few pixels (see first photo, where at the far right there's one line of pixels that should go to the left of the screen).

**Comment by jjwbruijn** [comment]
Helpful image! Fixed with commit cdd93df117dc1fb1af84a1e29bc48fa46ac0f63c
![image](https://user-images.githubusercontent.com/2544995/216193933-78241bde-3137-4860-8e26-3ebb53880429.png)
